### ISSUE TITLE
More Interpolation Options in Imrotate

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaImages/ImageTransformations.jl#111]
I was trying to implement more complicated interpolation options in imrotate, but seem to be restricted to passing arguments accepted by the BSpline interpolation class. Is it possible to use other interpolation classes like below?

using Interpolations imrotate(img,1.2,Lanczos4OpenCV())

(this produces an error message)

**Comment by timholy** [comment]
I'd be happy to accept a PR implementing this!
