### ISSUE TITLE
Images getting generated differently

### ISSUE THREAD

**Issue by SomTambe** [JuliaImages/ImageTransformations.jl#137]
I warp the same source image using Kornia and ImageTransformations, using the same homography matrix. I use a slightly modified function `warp_me2`, and the whole thing can be reproduced using [this repo](https://github.com/SomTambe/reproduction/tree/main/kornia%20vs%20julia) and running the `mytests.jl` file in it.

This is the image that I get in Kornia, which is actually very accurate - 
<img src="https://github.com/SomTambe/reproduction/raw/main/kornia%20vs%20julia/warp_kornia.jpeg" alt="drawing" width="300"/>

This is the image I get after warping it using the `warp_me2` function - 
<img src="https://github.com/SomTambe/reproduction/raw/main/kornia%20vs%20julia/warped_output_try_1.png" alt="drawing" width="300"/>

I've tried checking the individual indices to which it get warped, and their values, but they were all looking correct. I don't know why am I getting an issue here.

Any suggestions as to what is going wrong? Can someone checkout if they are facing the same issues?
The Kornia notebook can be accessed [here](https://github.com/kornia/kornia-examples/blob/master/homography.ipynb). The required files are all present in the reproduction repository above.

**Comment by johnnychen94** [comment]
- Instead of `h=homography2d(srcs,tgts)`, can you start with hardcoded transformation matrix?
- Instead of using big real images like this, can you try it on very small images (e.g., `reshape(collect(0:0.04:0.96), 5, 5)`)?

**Comment by SomTambe** [comment]
- I used `homography2d` to get the homography matrix, and then hardcoded that matrix to Kornia which gave me the above results. Therefore, I don't think `homography2d` is giving us a problem.
- I will try using smaller images as you have suggested.

**Comment by SomTambe** [comment]
I have gotten why this was going south. 
Plot.jl is plotting according to the transposed dimensions. Surprisingly, FileIO was also reading the images according to transposed dimensions.
`[i, j]` in images/array indexing mean that `i` is along the vertical axis and `j` is along the horizontal axis.
In Plots.jl, it plots the `i` along the horizontal axis and `j` along the vertical axis. Hence the issue.
With small changes, like this -
```julia
src_img = load("source.jpeg")'
tgt_img = load("target.jpeg")'
...
plot(mosaicview(tgt_img,warp_me2(src_img,h);nrow=1))
```
This is the correct warp I get, of course transposed image - 
<img src="https://github.com/SomTambe/reproduction/raw/main/kornia%20vs%20julia/correct_plot_julia.png" alt="drawing" width="300"/>

**Comment by johnnychen94** [comment]
I don't quite understand the meaning of the results, but since you figured it out I'm going to close it.
