### ISSUE TITLE
No stable version document is deployed

### ISSUE THREAD

**Issue by hyrodium** [JuliaImages/ImageTransformations.jl#139]
https://juliaimages.org/ImageTransformations.jl/stable returns 404.

We can add the old documentation by adding tags with metadata such as `v0.8.12+doc1`.
cf. https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions

**Comment by johnnychen94** [comment]
one last PR #138 and I'll tag a new release for it 😂

**Comment by hyrodium** [comment]
Ah, I've just noticed that `v0.8.12` doesn't include `docs` directory :joy:

**Comment by mkitti** [comment]
I just noticed this as well.

**Comment by johnnychen94** [comment]
The documentation is newly added and we haven't yet ready to make the breaking ImageTransformations v0.9

**Comment by mkitti** [comment]
Part of the issue the `Docs | Stable` link exists in the README. When I see that leads to a 404, then I think the documentation is not available. I might not have tried to click the `Docs | Dev` link to see if that worked.

**Comment by johnnychen94** [comment]
Given that we have some pending PRs to 0.9 release, I've done a manual cherry-pick to backport the docs change and make v0.8.13 release, no functionality change, only to trigger the docs building.
