### ISSUE TITLE
Image warping / OffsetArrays

### ISSUE THREAD

**Issue by fpreiswerk** [JuliaImages/ImageTransformations.jl#16]
I'm trying to understand and use the image transformation method described in http://juliaimages.github.io/latest/indexing.html

I'm trying to apply the same rotation as described in the above doc:
```
using Images, ImageView, TestImages, ImageTransformations, CoordinateTransformations
img = testimage("mandrill")
imgg = convert(Image{Gray}, img)
tfm = recenter(RotMatrix(pi/8), center(imgg))
imgrot = warp(imgg, tfm);
img0 = similar(imgrot);
fill!(img0, 0);
img0[1:512, 1:512] = img;
imgov = colorview(RGB, img0, imgrot, zeroarray)
```

although this works, when I try to display the image using

`imshow(imgov)`

I get the following error:

> ERROR: BoundsError: attempt to access -78:591×-78:591 ColorView{RGB}(::ImageCore.StackedView{Float64,3,Tuple{MappedArrays.MappedArray{Float64,2,OffsetArrays.OffsetArray{ColorTypes.Gray{Float64},2,Array{ColorTypes.Gray{Float64},2}},MappedArrays.##1#3{Float64},MappedArrays.##2#4{ColorTypes.Gray{Float64}}},MappedArrays.MappedArray{Float64,2,OffsetArrays.OffsetArray{ColorTypes.Gray{Float64},2,Array{ColorTypes.Gray{Float64},2}},MappedArrays.##1#3{Float64},MappedArrays.##2#4{ColorTypes.Gray{Float64}}},ImageCore.ZeroArray{Float64,2,UnitRange{Int64}}}}) with element type ColorTypes.RGB{Float64} at index [1:670,1:670] ...

This seems to have to do with the returned OffsetArray having negative indices.

Julia version: 0.5.0
Images: 0.8.0
ImageView: 0.3.1
TestImages: 0.2.0
ImageTransformations: 0.1.0
CoordinateTransformations: 0.4.0

Thank you.

**Comment by timholy** [comment]
Those docs were written when I thought I'd finish that work more quickly, but that didn't really happen... The whole display stack needs to become indices-aware. This is a high-priority project for me, but in the meantime just use
```julia
imgov = colorview(RGB, parent(img0), parent(imgrot), zeroarray);
```
if you want the whole range, or
```julia
imgov = colorview(RGB, imgg, imgrot[1:512,1:512], zeroarray);
```
if you want the same region spanned by the original image. Both of these versions strip away the unconventional indices (in different ways) using `parent` or explicit indexing.

**Comment by fpreiswerk** [comment]
That works. Many thanks, Tim!
