### ISSUE TITLE
Support v0.15 of Interpolations.jl

### ISSUE THREAD

**Issue by cgarling** [JuliaImages/ImageTransformations.jl#165]
Interpolations.jl v0.15.0 is now out and it would be nice to update this package's compat to support it. I tried to do this on my own fork so I could submit a PR but the new version of Interpolations.jl breaks the test on line 65 of `test/interpolations.jl` and I don't have time to look into why at the moment.

**Comment by roflmaostc** [comment]
Can be closed because of #168
