### ISSUE TITLE
Warnings on Julia v0.6

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageTransformations.jl#17]
>WARNING: deprecated syntax "typealias FloatLike{T<:AbstractFloat} Union{T,Gray{T}}" at /home/juliohm/.julia/v0.6/ImageTransformations/src/ImageTransformations.jl:10.
Use "FloatLike{T<:AbstractFloat} = Union{T,Gray{T}}" instead.

>WARNING: deprecated syntax "typealias FloatColorant{T<:AbstractFloat} Colorant{T}" at /home/juliohm/.julia/v0.6/ImageTransformations/src/ImageTransformations.jl:11.
Use "FloatColorant{T<:AbstractFloat} = Colorant{T}" instead.

**Comment by SimonDanisch** [comment]
If the warnings annoy you, please fix them :) We are all aware that there are warnings but probably no one has time to fix them right now, so an issue isn't really helping (a warning is not really an issue ;) )

**Comment by SimonDanisch** [comment]
Sure, point is, the person that knows the codebase likely knows about the warnings and obviously has decided, that there isn't time to fix them yet.
If you haven't noticed, the warning tells you exactly how to fix it in 5 seconds...

**Comment by Evizero** [comment]
fixed with the merge of #11
