### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageTransformations.jl#29]
Mind if we tag a new version with the current state? Could use it to make CI pass on a project I am working on and I am pressed on time a little

**Comment by Evizero** [comment]
I just went ahead and edited the CI scripts in said package, which I should have thought of first, really. Lets wait with a tag until I add the last missing couple tests.

sorry for the noise

**Comment by timholy** [comment]
No noise, sorry I was so slow to respond ("real work" is busy right now). I'd be happy to tag now, but if you prefer to wait for the tests that will be fine too. Bottom line, you should feel free to tag yourself if you like---you've contributed at least as much as I to this package, and your judgment is excellent, so I have no reservations of any kind having you make decisions.

**Comment by Evizero** [comment]
Thanks. I appreciate the sentiment
