### ISSUE TITLE
Use ReferenceTests.jl for testing instead of custom code 

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageTransformations.jl#39]
Since the [reference test code](https://github.com/JuliaImages/ImageTransformations.jl/blob/master/test/runtests.jl#L22-L70) is duplicated among three packages by now I made a little stand alone package for the reference tests. Once registered in METADATA I plan to replace the old manual code, which includes this package.

https://github.com/Evizero/ReferenceTests.jl

Unless there are objections of course. That said this will only be a `test/REQUIRE` dependency, and not really affect the actual package code

**Comment by timholy** [comment]
That seems great to me. It's really nice functionality, it deserves it's own repo.
