### ISSUE TITLE
warp question

### ISSUE THREAD

**Issue by jianghaizhu** [JuliaImages/ImageTransformations.jl#41]
The new `warp` function is bit different than the old `transform` from `AffineTransforms`. Suppose I have an array and I want to translate the array by `(x, y)` and fill the moved out rows and columns with `0`. How would I do that?  

If I want to translate and rotate the array, and keep the same size as the original array and fill with `0`, how should I use `warp`?

Thanks!

**Comment by Evizero** [comment]
probably easier to use `warp!` here, which is not exported I believe. 
Maybe we should try make preserving array size look nicer.

```julia
using Images, ImageTransformations, TestImages, CoordinateTransformations, Rotations
img = testimage("lighthouse")
tfm = recenter(RotMatrix(deg2rad(45)), ImageTransformations.center(img))
ImageTransformations.warp!(similar(img), ImageTransformations.box_extrapolation(img), tfm)
```

**Comment by Evizero** [comment]
by the way this `recenter` changes the transformation such that the rotation is done around the center of the original image. If you do translation you'll have to be mindful of that

**Comment by jianghaizhu** [comment]
Great! This works as I expected. I agree that there should be some options to preserve size. Also export `warp!` would be more convenient for users.  Thanks a lot!
