### ISSUE TITLE
NaNs contaminate warped image

### ISSUE THREAD

**Issue by Cody-G** [JuliaImages/ImageTransformations.jl#45]
I'm getting a surprising result when calling `warp` with an `IdentityTransformation`.  Is this a bug?

```julia
using Images, CoordinateTransformations, Interpolations
img = rand(4,8)
img[:,1:2] = NaN
img[:,7:8] = NaN
imgw = warp(img, IdentityTransformation(), indices(img), Linear(), Flat())
@show img
#Notice that column 6 gets set to NaN
@show parent(imgw)
```

Note that this doesn't happen when `Constant()` interpolation is used for the degree.  As for the fill parameter, `Flat()` and `NaN` give the same result.

**Comment by Evizero** [comment]
Interesting. Intuitively I'd guess this is because of interpolations. I'll take a look some i find some time

**Comment by Cody-G** [comment]
Great, thanks!  Let me know if I can help.

**Comment by Cody-G** [comment]
Yes this is definitely due to Interpolations.  I created and issue there.

**Comment by Evizero** [comment]
Thanks for looking into it. Will close this issue here then if it is upstream

**Comment by Cody-G** [comment]
Upstream views this as correct behavior and suggests that we special-case downstream code. @Evizero and @timholy what do you think is the best way forward?  We could special case `IdentityTransformation`s and  `Translation`s with all-integer coordinate shifts so that they don't interpolate at all.  That doesn't seem ideal because existing code probably expects to get an interpolation object back, and it also doesn't cover all of the possible cases where `NaN` values can be imputed at grid points (just the most annoying cases imo).
