### ISSUE TITLE
Could Warp function be used to do a projective transformation of an image using a 3x3 matrix?

### ISSUE THREAD

**Issue by tosalonijain** [JuliaImages/ImageTransformations.jl#46]
I am interested to know if warp function defined in this repository work similar to the _warp_fast function available in scipy for homography ?

**Comment by Evizero** [comment]
I don't know the function you speak of. The gist of warp is that it uses https://github.com/FugroRoames/CoordinateTransformations.jl to represent transformations. so if you can represent it using what that package provides it should more or less work. 

I am pretty sure we would need some custom tweaking somewhere though as I believe `LinearMap` and `AffineMap` both make the assumption that the first two elements of the 3x3 transformation matrix are zero and thus just omits them entirely.

**Comment by johnnychen94** [comment]
This seems to be a very similar question to #64 so I'll close it.

The short answer is yes, as long as you wrap it with a function that inputs a `SVector` and outputs a `SVector`. https://github.com/JuliaGeometry/CoordinateTransformations.jl is a convenient package that could possibly create such a function (although I didn't put my hands on it).
