### ISSUE TITLE
restrict produces wrong boundary values if called with a one-row array

### ISSUE THREAD

**Issue by johanneslotz** [JuliaImages/ImageTransformations.jl#47]
I guess the following example illustrates the problem quite well.

```julia
julia> restrict([0 1 0][:])
2-element Array{Float64,1}:
 0.25
 0.25

julia> restrict([0 1 0])
1×2 Array{Float64,2}:
 0.25  1.75543e13
```

While this is obviously not the intended use case, it happened to me accidentally not realizing that I should use a Vector instead of a 2D Array.

**Comment by Evizero** [comment]
interestingly i don't quite get the same result

```julia
julia> restrict([0 1 0][:])
2-element Array{Float64,1}:
 0.25
 0.25

julia> restrict([0 1 0])
1×2 Array{Float64,2}:
 0.25  0.125
```

**Comment by johanneslotz** [comment]
I am using julia version 0.6.2 on Linux and a fresh Pkg.add("Images") (today, in a separate docker container). I am also seeing this on my Mac (also on 0.6.2, packages are not all up-to-date).

My results are changing from time to time. I got your results a few minutes ago but after adding and removing a few zeros and spaces, I get very large (changing) numbers again in the last component. Looks like some memory corruption.

```julia
julia> restrict([0 0 0 1 0])
1×3 Array{Float64,2}:
 0.0  0.25  0.125

julia> restrict([0 0 0 1 0])
1×3 Array{Float64,2}:
 0.0  0.25  1.75809e13
```

**Comment by Evizero** [comment]
maybe there are multiple issues here. I'll have to look into it when I find some time. Thanks for opening the issue.

**Comment by Evizero** [comment]
Ok i found the culprit. You were correct in your assumption. It is in fact a out-of-bounds memory access hidden by the `@inbounds` macro here: https://github.com/JuliaImages/ImageTransformations.jl/blob/master/src/resizing.jl#L126-L136

Unsure what the proper way to fix this is. One option is to make restricting a length 1 dimension a noop. Another option is to to just throw a more informative error message.
