### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageTransformations.jl#5]
Probably a good idea. Surely someone at METADATA will point out the lack of travis testing :)

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/7944#issuecomment-279473923

**Comment by timholy** [comment]
AppVeyor should be on now.

**Comment by timholy** [comment]
Oh, Travis wasn't on either. Next PR, both with be.
