### ISSUE TITLE
Move restrict to a faster loading package?

### ISSUE THREAD

**Issue by IanButterworth** [JuliaImages/ImageTransformations.jl#69]
Is there a way to get the restrict function with faster load times?

```
julia> @time using ImageTransformations: restrict
  3.119409 seconds (6.69 M allocations: 376.407 MiB, 4.46% gc time)
julia> exit()
...
julia> @time using ImageTransformations: restrict
  3.212386 seconds (6.69 M allocations: 376.411 MiB, 4.51% gc time)
```

**Comment by johnnychen94** [comment]
@timholy how do you think of moving `restrict` to `ImageCore`? That way `ImageShow` could also benefit from this.

**Comment by timholy** [comment]
I'm supportive of the idea of splitting it out but a bit reluctant to move it to ImageCore, simply because there are no other "algorithms" in there: it's all traits and views.

We could make a separate ImageUtils package and put it there. We could also split out a subpackage from this one and register it separately, e.g., `ImageTransformationsRestrict`, and it could continue living here. Other thoughts?

**Comment by johnnychen94** [comment]
Haven't tried it out, but perhaps we could take advantage of https://github.com/JuliaPackaging/Preferences.jl to come up with a way to lazily compile the module, i.e., if we only need a function, then only compile related parts?

**Comment by ianshmean** [comment]
It's been a while since I opened this issue.. and load time (and precomp time) has, as expected, improved with 1.6
```
julia> @time using ImageTransformations
  1.839368 seconds (3.92 M allocations: 285.683 MiB, 4.28% gc time, 18.44% compilation time)
```

I'm not too worried anymore, but don't let that stall the idea if you think it's still worth it

**Comment by johnnychen94** [comment]
among the 1.8seconds using time, about 0.8 seconds are contributed by `Interpolations`/`CoordinationTransformations`/`StaticArrays`, so it definitely worth if we can skip loading them; especially it will be more convenient if we can make ImageShow always loaded with the better `restrict` implementation.

**Comment by johnnychen94** [comment]
I plan to make `ImageUtils` on top of `ImageCore`, and then move `restrict` there.

Because the main purpose of `ImageUtils` is to boost loading time, it needs to be very conservative to outside dependencies.
