### ISSUE TITLE
Inconsistencies for imrotate() docs

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaImages/ImageTransformations.jl#90]
In warp.jl a docstring example for `imrotate` says:
```julia
# rotate with bilinear interpolation and with cropping
julia> imrotate(img, π/4, axes(img)
```
This works, but is confusing for two reasons. First, the option to put axes into the arguments isn't in the usage line of the docstring. Second, it fails when specifying degree and/or extrapolation other than the defaults. A more robust alternative is  
```julia
imrotate(img, π/4)[axes(img)...]
```

Also, the references to `Constant()`, etc. and `Flat()`, etc. are unknown unless the user has imported `Interpolations.jl`. Maybe clarify, or just reexport that?

**Comment by johnnychen94** [comment]
I noticed the docstring issue once but forgot to update that, would you mind to open a PR for it? Feel free to reword it.

Advanced usage of this package does require a portion of `Interpolations` symbols imported but not all of them are required. Hence I prefer not to reexport the whole package. However, I'm open to changes.
